Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-3.2-1B-Instruct and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-3.2-1B-Instruct and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.











Map (num_proc=4): 100%|█████████████████████████████████████████████████████████████████| 116722/116722 [00:21<00:00, 5498.18 examples/s]
  0%|                                                                                                          | 0/29181 [00:00<?, ?it/s]

  0%|                                                                                                          | 0/29181 [00:00<?, ?it/s]From v4.47 onwards, when a model cache is to be returned, `generate` will return a `Cache` instance instead by default (as opposed to the legacy tuple of tuples format). If you want to keep returning the legacy format, please set `return_legacy_cache=True`.
{'eps': 0, 'objective/kl': 3.320620536804199, 'objective/entropy': 56.7608757019043, 'objective/non_score_reward': -0.16603104770183563, 'objective/rlhf_reward': 0.6906684041023254, 'objective/scores': 0.8566994667053223, 'policy/approxkl_avg': 0.2536434531211853, 'policy/clipfrac_avg': 0.012578615918755531, 'loss/policy_avg': 6.407033652067184e-05, 'loss/value_avg': 1.2008991241455078, 'val/clipfrac_avg': 0.0, 'policy/entropy_avg': 0.9581243991851807, 'val/ratio': 0.994469165802002, 'val/ratio_var': 2.5918538085534237e-05, 'val/num_eos_tokens': 0, 'lr': 0.0, 'episode': 12, 'epoch': 0.0}
  0%|                                                                                              | 1/29181 [00:13<108:50:32, 13.43s/it]Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yutong-8gpus-training/code/Users/yutong.jiang2/Pretrain_LLM/PPO/PPO.py", line 50, in <module>
    trainer.train()
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 577, in train
    self.generate_completions(sampling=True)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 619, in generate_completions
    for batch in self.eval_dataloader:
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/accelerate/data_loader.py", line 552, in __iter__
    current_batch = next(dataloader_iter)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 672, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 620, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 278, in __iter__
    sampler_iter = iter(self.sampler)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 112, in __iter__
    return iter(range(len(self.data_source)))
TypeError: object of type 'NoneType' has no len()